---
- name: let read interfaces from interfaces
  lineinfile:
    dest: "/etc/network/interfaces"
    line: "source /etc/network/interfaces.d/*"
  notify:
    - restart networking

- name: Konfig für die nat-Schnittstelle
  template:
    src: "vrf.j2"
    dest: "/etc/network/interfaces.d/00_vrf.cfg"
  notify:
    - restart networking

- name: Konfig für vrfs im sysctl
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.d/ff-vrf.conf"
  notify:
    - reload sysctl
