- name: reload sshd
  systemd:
    name: ssh
    state: reloaded

- name: reload resolv config
  command: resolvconf -u

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
