---
- name: configure bird
  shell: birdc configure || systemctl restart bird

- name: configure bird6
  shell: birdc6 configure || systemctl restart bird6

- name: restart bird
  systemd:
    name: bird
    state: restarted
    enabled: yes

- name: restart bird6
  service:
    name: bird6
    state: restarted
    enabled: yes

- name: reread systemd configs
  systemd:
    daemon_reload: yes

