---
- name: reload bird
  systemd:
    name: bird
    state: reloaded

- name: reload bird6
  systemd:
    name: bird6
    state: reloaded

- name: reread systemd configs
  systemd:
    daemon_reload: yes

