---
- name: Increase Kernel default rx buffersize
  sysctl:
    name: net.core.rmem_default
    value: 26214400
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase Kernel max rx buffersize
  sysctl:
    name: net.core.rmem_max
    value: 26214400
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase Kernel max optmem buffersize
  sysctl:
    name: net.core.optmem_max
    value: 81920
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Increase max queue len of unhandled rx packets in Kernel
  sysctl:
    name: net.core.netdev_max_backlog
    value: 5000
    state: present
    reload: yes
  notify:
    - "restart hopglass"

- name: Create HopGlass-server directory if not existent
  file:
    path: /opt/hopglass
    state: directory

- name: Create HopGlass User
  user:
    name: hopglass
    system: yes
    createhome: yes
    home: /opt/hopglass

- name: Clone HopGlass Server Repo
  git:
    repo: https://github.com/hopglass/hopglass-server.git
    dest: /opt/hopglass/server
  notify:
    - "restart hopglass"
  register: hopglass_server_git_clone

- name: Add nodejs and yarn repo keys
  apt_key:
    id: "{{ item.id }}"
    url: "{{ item.url }}"
    state: present
  loop:
    - { id: '1655A0AB68576280', url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key' }
    - { id: '1646B01B86E50310', url: 'https://dl.yarnpkg.com/debian/pubkey.gpg' }

- name: Add repo for nodejs and yarn
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "deb https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_16.x {{ ansible_distribution_release }} main"
    - "deb https://dl.yarnpkg.com/debian/ stable main"

- name: Install nodejs and yarn
  apt:
    pkg: ['nodejs', 'yarn']
    state: present

- name: Adjust permissions
  file:
    path: /opt/hopglass
    owner: hopglass
    group: hopglass
    recurse: yes
  when: hopglass_server_git_clone.changed

- name: install dependencies
  shell: yarn install
  args:
    chdir: /opt/hopglass/server
  when: not ansible_check_mode and hopglass_server_git_clone.changed

- name: Create HopGlass-server Config directory if not existent
  file:
    path: /etc/hopglass-server/default
    state: directory

- name: Setup systemd service
  copy:
    src: /opt/hopglass/server/hopglass-server@.service
    dest: /lib/systemd/system/
    remote_src: True

- name: Adjust permissions of /etc/hopglass-server
  file:
    path: /etc/hopglass-server
    owner: hopglass
    group: hopglass
    recurse: yes

- name: Copy config.json
  template: 
    src: config.json.j2 
    dest: /etc/hopglass-server/default/config.json
    owner: hopglass
    group: hopglass
    mode: 0644
  notify:
    - "restart hopglass"

- name: Install jq for delnode script
  apt:
    pkg: jq
    state: present

- name: Copy delnode helper script
  copy:
    src: delnode
    dest: /usr/bin/delnode
    mode: a+x

- name: install hopglass server service hopglass-server
  service: 
    name: hopglass-server@default
    enabled: yes
