---
- name: Tunnels between backbones
  template: src="gre_interbackbone.j2" dest="/etc/network/interfaces.d/42_gre_interbackbone.cfg"
  notify: restart networking

#append line in interfaces file for reading additional config files
- name: let read interfaces.d from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source-directory /etc/network/interfaces.d/"
  notify: restart networking
