---
- name: Tunnels between backbones
  template: src="gre_interbackbone.j2" dest="/etc/network/interfaces.d/42_gre_interbackbone.cfg"
  notify: restart networking

- name: Routingtabelle 42 auch ffnet nennen
  blockinfile:
    path: "/etc/iproute2/rt_tables"
    marker: "# {mark} Ansible managed block"
    block: |
      42   ffnet

#append line in interfaces file for reading additional config files
- name: let read interfaces.d from interfaces
  lineinfile: dest="/etc/network/interfaces" line="source /etc/network/interfaces.d/*"
  notify: restart networking
