 - name: check for ifupdown2
   stat: path=/sbin/ifreload
   register: ifreload

 - name: install dependencies (for compilation and runtime)
   apt:
     pkg: ['build-essential', 'devscripts', 'dh-systemd', 'fakeroot', 'python-all', 'python-docutils', 'iproute2', 'python-ipaddr', 'python-setuptools', 'dh-python', 'python3-all', 'python3-setuptools', 'python3-docutils', 'ethtool', 'bridge-utils', 'python-gvgen', 'python-mako']
     state: present
   when: ifreload.stat.exists == False

 - name: clone repository
   git:
     repo: 'https://github.com/CumulusNetworks/ifupdown2.git'
     dest: /opt/ifupdown2
     version: master
     update: yes
     force: yes
   when: ifreload.stat.exists == False

 - name: compile and create deb
   shell: "dpkg-buildpackage -us -uc -rfakeroot -b"
   args:
     chdir: "/opt/ifupdown2"
   when: ifreload.stat.exists == False

 - name: install created deb package
   shell: "dpkg -i /opt/ifupdown2*deb"
   when: ifreload.stat.exists == False
