# This role builds ISC KEA for running PostgreSQL as Database engine
---
- name: Install required packages for building KEA
  apt:
    pkg: ['git', 'g++', 'automake', 'autoconf', 'libtool', 'pkg-config', 'libboost-all-dev', 'openssl', 'libssl-dev', 'ca-certificates', 'liblog4cplus-dev', 'postgresql-server-dev-all', 'libpq-dev']
    update_cache: yes
    cache_valid_time: 1800
    state: present
    install_recommends: no
  when: domaenenliste is defined

- name: Clone ISC KEA git repo and checkout release Kea-1.6.0 
  git: 
    repo: https://github.com/isc-projects/kea.git
    dest: /srv/kea
    clone: yes
    update: no
    version: Kea-1.6.0
  when: domaenenliste is defined

- name: Build ISC KEA
  shell: "{{item}}"
  args:
    chdir: "/srv/kea"
    creates: "/usr/local/sbin/kea-dhcp4"
  with_items:
    - "autoreconf --install"
    - "./configure --with-pgsql"
    - "make -j $(grep -ic 'model name' /proc/cpuinfo)"
    - "make install"
    - "ldconfig"
  when: domaenenliste is defined

- name: Depoly systemd files
  template:
    src: "{{item}}"
    dest: "/lib/systemd/system/{{item[:-3]}}"
  with_items:
    - kea-dhcp4.service.j2
    - kea-dhcp6.service.j2
    - kea-dhcp-ddns.service.j2
  notify:
    - reload systemd
  when: domaenenliste is defined

- name: Deploy logrotate template file
  template:
    src: logrotate-kea-dhcp4.j2
    dest: /etc/logrotate.d/kea-dhcp4
  when:
    - domaenenliste is defined
