# batman-adv

# Prüfen ob DKMS installiert ist
- name: Prüfe ob dkms verfügbar ist
  stat:
    path: /usr/sbin/dkms
  register: stat_dkms
  changed_when: False
  check_mode: no

# Evtl. vorhandenes batman-adv-DKMS-Modul deinstallieren
- name: Prüfe ob batman-adv als DKMS-Modul installiert wurde
  shell: |
    set -o pipefail
    dkms status batman-adv -k {{ ansible_kernel }} | grep -Eo '[[:digit:]]{4}\.[[:digit:]](\.[[:digit:]])?' || true
  args:
    executable: bash
  register: dkms_version_batman
  when: stat_dkms.stat.exists
  changed_when: False
  check_mode: no

- name: DKMS-Modul batman-adv entfernen
  shell: "dkms remove batman-adv/{{ dkms_version_batman.stdout }} -k {{ ansible_kernel }} || rm -rf /var/lib/dkms/batman-adv/{{ dkms_version_batman.stdout }}"
  when: stat_dkms.stat.exists and dkms_version_batman.stdout
  notify: restart batman

# batctl
- name: /usr/local/sbin/batctl löschen
  file:
    path: /usr/local/sbin/batctl
    state: absent
