- name: install fail2ban
  apt:
    pkg: ['fail2ban']
    state: present

- name: generate default.local
  template: 
    src: default.local.j2
    dest: /etc/fail2ban/jail.d/default.local
  notify:
    - "restart fail2ban"

- name: check if rsyslog is installed
  command: which rsyslogd
  register: rsyslog_check
  ignore_errors: true

- name: set fail2ban lookup-method by setting fact for backend_systemd
  set_fact:
    backend_systemd: "{{ rsyslog_check.rc != 0 }}"

- name: generate sshd.local
  template: 
    src: sshd.local.j2
    dest: /etc/fail2ban/jail.d/sshd.local
  notify:
    - "restart fail2ban"
