---
- name: restart fastd per domain
  systemd:
    name: fastd@{{ item.key }}.service
    state: restarted
  when: item.value.fastd is defined and item.value.fastd
  with_dict: "{{ domaenenliste }}"

- name: reread systemd configs
  systemd:
    daemon_reload: yes

