---
- name: let read interfaces from interfaces
  lineinfile:
    dest: "/etc/network/interfaces"
    line: "source-directory /etc/network/interfaces.d/"
  notify:
    - restart networking

- name: Konfig für die nat-Schnittstelle
  template:
    src: "vrf.j2"
    dest: "/etc/network/interfaces.d/00_vrf.cfg"
  notify:
    - restart networking

- name: Konfig für vrfs im sysctl
  template:
    src: "sysctl.conf.j2"
    dest: "/etc/sysctl.d/ff-vrf.conf"
  notify:
    - reload sysctl

- name: Create /etc/iproute2/rt_tables.d/ directory if it does not exist
  ansible.builtin.file:
    path: /etc/iproute2/rt_tables.d/
    state: directory
    mode: '0755'

- name: Patch VRF-Executor
  ansible.posix.patch:
    src: vrf_exit.patch
    dest: /usr/libexec/ifupdown-ng/vrf
