---

- name: restart icinga2
  service:
    name: icinga2
    state: restarted
    enabled: yes

- name: reload apache2
  service:
    name: apache2
    state: reloaded
    enabled: yes

- name: update-exim4.conf
  shell: update-exim4.conf
