---

- name: restart icinga2
  service:
    name: icinga2
    state: restarted

- name: reload apache2
  service:
    name: apache2
    state: reloaded

- name: reload exim4
  service:
    name: exim4
    state: reloaded

- name: update-exim4.conf
  shell: update-exim4.conf
