- name: Install dependencies for building borgbackup
  apt:
    pkg: ['python3', 'python3-dev', 'python3-pip', 'python-virtualenv', 'libssl-dev', 'openssl',
         'libacl1-dev', 'libacl1', 'liblz4-dev', 'liblz4-1', 'build-essential']
    state: present
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04') or
        (ansible_distribution == 'Debian' and ansible_distribution_version == '9')

- name: Install borgbackup from source
  pip:
    name: ['borgbackup==1.1.0']
    state: present
    executable: pip3
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04') or
        (ansible_distribution == 'Debian' and ansible_distribution_version == '9')

- name: Install borgbackup from repository
  apt:
    pkg: ['borgbackup']
  when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04') and
        not (ansible_distribution == 'Debian' and ansible_distribution_version == '9')
