- name: install gluon dependencies
  apt:
    name: ['ca-certificates', 'file', 'git', 'subversion', 'python3', 'build-essential', 'gawk', 'unzip', 'libncurses5-dev', 'zlib1g-dev', 'libssl-dev', 'libelf-dev', 'wget', 'rsync', 'time', 'qemu-utils', 'ecdsautils', 'lua-check', 'shellcheck']
    update_cache: true
    install_recommends: false

- name: Create gits directory
  file:
    path: /root/gits
    state: directory

- name: Clone tools repo
  git:
    repo: git@github.com:FreiFunkMuenster/tools.git
    dest: /root/gits/tools
    accept_hostkey: true

- name: Clone gluon repo
  git:
    repo: https://github.com/freifunk-gluon/gluon.git
    dest: /root/gits/gluon
