---

- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    masked: yes

- name: Install ntp
  apt: name=ntp

- name: Install ntp.conf
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: Restart ntpd
