---

- name: Disable systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: stopped
    masked: yes

- name: Install ntp
  apt:
    name: ntp

- name: Install ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify: Restart ntpd

- name: create folder for ntp service override file
  file:
    path: /etc/systemd/system/ntp.service.d
    state: directory
    mode: 0755

- name: override ntp service
  template:
    src: ntp.service.override.j2
    dest: /etc/systemd/system/ntp.service.d/ansible-managed.conf
  notify:
    - reread systemd configs
    - Restart ntpd
